# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - ".pub-cache"
stages:
- test
- build
- deploy
flutter_analyze:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
  - flutter pub get
  script:
  - flutter analyze
build_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
  - flutter pub get
  script:
  - flutter build web --base-href "/"
  artifacts:
    paths:
    - build/web
    expire_in: 1 week
build_android_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
  - flutter pub get
  script:
  - flutter build apk --release
  artifacts:
    paths:
    - build/app/outputs/flutter-apk
    expire_in: 1 week
deploy_preview:
  stage: deploy
  image: node:16.16.0
  except:
  - main
  dependencies:
  - build_web_app
  script:
  - npm install --global vercel
  - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
  - mkdir -p public
  - cp -r build/web/. public/
  - vercel build --token=$VERCEL_TOKEN
  - vercel deploy --prebuilt --token=$VERCEL_TOKEN
deploy_production:
  stage: deploy
  image: node:16.16.0
  only:
  - main
  dependencies:
  - build_web_app
  script:
  - npm install --global vercel
  - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
  - mkdir -p public
  - cp -r build/web/. public/
  - vercel build --prod --token=$VERCEL_TOKEN
  - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
include:
- template: Security/SAST-IaC.latest.gitlab-ci.yml
