cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pub-cache

stages:
  - test
  - build
  - deploy

# Flutter Analyze Job
flutter_analyze:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter analyze
  
# Flutter check Code-Quality
code_quality:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week

# Web Build
build_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build web --base-href "/"
  artifacts:
    paths:
      - build/web
    expire_in: 1 week

# Android Build
build_android_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk
    expire_in: 1 week

# Deploy Preview for Web
deploy_preview:
  stage: deploy
  image: node:16.16.0
  except:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

# Deploy Production for Web
deploy_production:
  stage: deploy
  image: node:16.16.0
  only:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN