build_and_test_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - cd demo_app
    - flutter pub get
  script:
    - flutter build web --base-href "/Squash-Tracker/"
    - flutter analyze
  artifacts:
    paths:
      - demo_app/build/web
 
pages:
  stage: deploy
  script:
    - cp -r demo_app/build/web/* public
  artifacts:
    paths:
      - public
  only:
    - main