#Cache for builds
cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .pub-cache
  policy: pull-push

stages:
  - test
  - build
  - deploy

dependencies_install:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - flutter pub get
  cache:
    key: "pub-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - .pub-cache

# Flutter Analyze Job
flutter_analyze:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  dependencies:
    - dependencies_install
  script:
    - flutter analyze

# Flutter Test
flutter_test:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  dependencies:
    - dependencies_install
  script:
    - flutter test
  artifacts:
    paths:
      - test-report.json
    expire_in: 1 week

# Web Build
build_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - flutter build web --base-href "/" --dart-define="SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" --dart-define="SUPABASE_URL=${SUPABASE_URL}"
  artifacts:
    paths:
      - build/web
    expire_in: 1 week

# Android Build
build_android_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - flutter build apk --dart-define="SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" --dart-define="SUPABASE_URL=${SUPABASE_URL}"
  artifacts:
    paths:
      - build/app/outputs/flutter-apk
    expire_in: 1 week

# Deploy Preview for Web
deploy_preview:
  stage: deploy
  image: node:16.16.0
  needs: [build_web_app]
  except:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

# Deploy Production for Web
deploy_production:
  stage: deploy
  image: node:16.16.0
  only:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN