# Web Build and Test
build_and_test_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build web --base-href "/"
    - flutter analyze
  artifacts:
    paths:
      - build/web

# Windows Build
build_and_test_windows_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build windows
    - flutter analyze
  artifacts:
    paths:
      - build/windows

# Android Build
build_and_test_android_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build apk --release
    - flutter analyze
  artifacts:
    paths:
      - build/app/outputs/flutter-apk

# Deploy Preview for Web
deploy_preview:
  stage: deploy
  image: node:16.16.0
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

# Deploy Production for Web
deploy_production:
  stage: deploy
  image: node:16.16.0
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN