build_and_test_web_app:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  before_script:
    - cd demo_app
    - flutter pub get
  script:
    - flutter build web --base-href "/"
    - flutter analyze
  artifacts:
    paths:
      - demo_app/build/web

#pages:
#  stage: deploy
#  script:
#    - mkdir -p public
#    - cp -r demo_app/build/web/. public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - main
    
deploy_preview:
  stage: deploy
  image: node:16.16.0
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r demo_app/build/web/. public/
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  image: node:16.16.0
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r demo_app/build/web/. public/
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
