# Set YAML anchors as const variables
.default_flutter: &default_flutter
  image: ghcr.io/cirruslabs/flutter:stable
.default_node: &default_node
  image: node:22-alpine

# Cache for builds
cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .pub-cache
    - .dart_tool/
  policy: pull-push

# Define stages
stages:
  - test
  - build
  - deploy

# Flutter install necessary dependencies
dependencies_install:
  stage: test
  <<: *default_flutter
  script:
    - flutter pub get
  cache:
    key: "pub-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - .pub-cache

# Flutter Analyze Job
analyze:
  stage: test
  <<: *default_flutter
  dependencies:
    - dependencies_install
  script:
    - flutter analyze

# Flutter Test
test:
  stage: test
  <<: *default_flutter
  dependencies:
    - dependencies_install
  script:
    - flutter test --machine > test-report.json
  artifacts:
    paths:
      - test-report.json
    expire_in: 1 week

# Web Build
build_web_app:
  stage: build
  <<: *default_flutter
  script:
    - flutter build web --base-href "/" --dart-define="SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" --dart-define="SUPABASE_URL=${SUPABASE_URL}"
  artifacts:
    paths:
      - build/web
    expire_in: 1 week

# Android Build
build_android_app:
  stage: build
  <<: *default_flutter
  script:
    - flutter build apk --dart-define="SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" --dart-define="SUPABASE_URL=${SUPABASE_URL}"
  artifacts:
    paths:
      - build/app/outputs/flutter-apk
    expire_in: 1 week

# Deploy Preview for Web
deploy_preview:
  stage: deploy
  <<: *default_node
  needs: [build_web_app]
  except:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

# Deploy Production for Web
deploy_production:
  stage: deploy
  <<: *default_node
  only:
    - main
  dependencies:
    - build_web_app
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mkdir -p public
    - cp -r build/web/. public/
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

    #just test