image: cirrusci/flutter:latest

stages:
  - build
  - deploy

build_android:
  stage: build
  script:
    - flutter packages get
    - flutter build apk --release

deploy_android:
  stage: deploy
  script:
    - flutter build appbundle --release
    - echo "Deploying to Google Play Store"
