name: squash_tracker
description: A Squash-Tracker-App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  supabase_auth_ui: ^0.5.4
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.4
  choice: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true